### ISSUE TITLE
Consiglio

### ISSUE THREAD

**Issue by Baraff24** [Deggio-s-digital/python-classeviva-api#1]
Se dovete fare un backend poggiandovi sulle API di classeviva, sarebbe meglio utilizzare un framework (come Django) per gestire al meglio le richieste e rendere il progetto sicuro e scalabile. Quel codice sembra scritto con copilot o copiato da qualche parte, perché ci sono molte cose che potrebbero essere gestite meglio inoltre sono scritte in maniera poco comprensibile.
In bocca al lupo :)

**Comment by FrancescoLFM** [comment]
Ciao, grazie per aver visualizzato il nostro progetto.
Non ho utilizzato un framework per il semplice motivo che non sono molto avvezzo nel campo del web development e credo che sia non necessario e overkill per i nostri scopi.
Riguardo il codice, è tutto scritto da me ed è ancora incompleto, non ho utilizzato nessun tipo di copilot (Anche se non saprei come dimostrarlo), quindi potresti segnalarmi le righe di codice che sono poco comprensibili?

Grazie,

Francesco Pallara

**Comment by Baraff24** [comment]
Un framework non è sempre qualcosa di pesante e "_overkill_"... Esistono framework Python per lo sviluppo web più leggeri come Flask. il codice è organizzato in maniera confusa quindi non si riesce a delineare un "flow" in maniera chiara, sicuramente un file "ReadMe" avrebbe aiutato. Per una migliore spiegazione di ciò che intendo di suggerisco di leggere questo: [Zen of Python](https://peps.python.org/pep-0020/). Un ultimo consiglio: per i progetti open-source è bene delineare una descrizione esaustiva prima di iniziare il progetto, per permettere a tutti di poter contribuire al progetto. Detto ciò vi auguro in bocca al lupo :)

**Comment by FrancescoLFM** [comment]
Era nei programmi la scrittura del readme (magari dopo aver rifinito la codebase). Grazie di nuovo per il consiglio sul framework.

Arrivederci,

Francesco Pallara
